Repository kho-ja/appuri-hogosha, pull requests merged in 2025-08, with the labels that each got.

#264 change header style and remove password strength indicator
  mobile-frontend/app/(app)/(tabs)/(settings)/_layout.tsx
  mobile-frontend/app/(app)/(tabs)/(settings)/change-psswd.tsx
  mobile-frontend/app/(app)/(tabs)/(settings)/settings.tsx
Labels: bug

#310 feat: add deep link support for message access
  admin-panel-frontend/app/[locale]/(auth)/login/page.tsx
  admin-panel-frontend/app/[locale]/(dashboard)/(routes)/admins/page.tsx
  admin-panel-frontend/app/[locale]/(dashboard)/(routes)/fromKintone/parent/page.tsx
  admin-panel-frontend/app/[locale]/(dashboard)/(routes)/fromKintone/student/page.tsx
  admin-panel-frontend/app/[locale]/(dashboard)/(routes)/messages/[messageId]/page.tsx
  admin-panel-frontend/app/[locale]/(dashboard)/(routes)/messages/create/page.tsx
  admin-panel-frontend/app/[locale]/(dashboard)/(routes)/parents/page.tsx
  admin-panel-frontend/app/[locale]/(dashboard)/(routes)/students/page.tsx
  admin-panel-frontend/app/[locale]/(public)/parentnotification/[[...slug]]/page.tsx
  admin-panel-frontend/components/ParentTable.tsx
  admin-panel-frontend/components/StudentTable.tsx
  admin-panel-frontend/lib/kintoneUrlValidator.ts
  admin-panel-frontend/lib/useApiPostQuery.tsx
  admin-panel-frontend/messages/en.json
  admin-panel-frontend/messages/ja.json
  admin-panel-frontend/messages/ru.json
  admin-panel-frontend/messages/uz.json
  admin-panel-frontend/middleware.ts
  backend/src/routes/admin-panel/admin.ts
  backend/src/routes/admin-panel/group.ts
  backend/src/routes/admin-panel/parent.ts
  backend/src/routes/admin-panel/post.ts
  backend/src/routes/admin-panel/student.ts
  backend/src/utils/validate.ts
  mobile-frontend/+native-intent.ts
  mobile-frontend/app/_layout.tsx
  mobile-frontend/native-intent.ts
  mobile-frontend/package-lock.json
  mobile-frontend/package.json
  mobile-frontend/utils/deep-link-tester.ts
  push-notification/src/debug-push-notifications.ts
  push-notification/src/services/aws/pinpoint.ts
  push-notification/src/services/database/queries.ts
  push-notification/src/services/expo/push.ts
  push-notification/src/services/telegram/bot.ts
  push-notification/src/test-notification-token.ts
  push-notification/src/types/events.ts
  push-notification/src/utils/localization.ts
Labels: codex

#323 Sign in pagesidagi kamchiliklar to'g'irlandi
  mobile-frontend/app/forgot-password.tsx
  mobile-frontend/translations/translation.ts
  mobile-frontend/types/i18n.ts
Labels: dependencies
