Repository kho-ja/appuri-hogosha, pull requests merged in 2025-07, with the labels that each got.

#221 mobile goBack button fix
  mobile-frontend/app/(app)/(tabs)/(home)/_layout.tsx
  mobile-frontend/app/(app)/(tabs)/(home)/student/[id].tsx
Labels: bug

#232 frontend change password
  mobile-frontend/app/(app)/(tabs)/(settings)/_layout.tsx
  mobile-frontend/app/(app)/(tabs)/(settings)/change-psswd.tsx
  mobile-frontend/components/PasswordRequirements.tsx
  mobile-frontend/components/atomic/input.tsx
  mobile-frontend/translations/translation.ts
  mobile-frontend/types/i18n.ts
Labels: bug, help wanted

#239 fixed email ko’rinmay qolyapti va boshqa odamni kredentiali ketib qol…
  backend/src/routes/mobile/auth.ts
  mobile-frontend/app/(app)/(tabs)/(settings)/settings.tsx
  mobile-frontend/app/new-psswd.tsx
  mobile-frontend/contexts/auth-context.tsx
Labels: bug

#245 Mobile settings page dizayini yengisiga o'zgartirildi
  mobile-frontend/app/(app)/(tabs)/(settings)/settings.tsx
  mobile-frontend/components/ThemeSwitcher.tsx
  mobile-frontend/translations/translation.ts
  mobile-frontend/types/i18n.ts
Labels: dependencies
