Repository kho-ja/appuri-hogosha, pull requests merged in 2025-09, with the labels that each got.

#342 341 push tsuchi top page
  mobile-frontend/app.config.js
  mobile-frontend/native-intent.ts
Labels: bug, eas-build-android:preview

#347 fix deeplinking if 1 student
  mobile-frontend/app/_layout.tsx
  mobile-frontend/components/StudentSelector.tsx
  mobile-frontend/contexts/student-context.tsx
  mobile-frontend/native-intent.ts
Labels: bug, eas-build-android:preview

#376 fixed bug with 2 alert notif in ios
  mobile-frontend/app/AppWithNotifications.tsx
Labels: bug

#378 fixed ui language buttons padding
  mobile-frontend/app/language-select.tsx
Labels: bug

#391 chore: update dependencies and translations
  mobile-frontend/app/(app)/(tabs)/(home)/index.tsx
  mobile-frontend/app/(app)/(tabs)/(settings)/settings.tsx
  mobile-frontend/app/(app)/_layout.tsx
  mobile-frontend/app/_layout.tsx
  mobile-frontend/app/language-select.tsx
  mobile-frontend/babel.config.js
  mobile-frontend/components/FontSizeSlider.tsx
  mobile-frontend/components/ZoomGallery.tsx
  mobile-frontend/contexts/student-context.tsx
  mobile-frontend/package-lock.json
  mobile-frontend/package.json
  mobile-frontend/translations/translation.ts
  mobile-frontend/types/i18n.ts
Labels: eas-build-android:preview

#386 fixed read status group if messages in the group
  mobile-frontend/app/(app)/(tabs)/(home)/student/[studentId]/message/[id].tsx
Labels: bug
