Repository kho-ja/appuri-hogosha, pull requests merged in 2025-04, with the labels that each got.

#91 fixing env problem in mobile and making mobile consistent again. Some changes from @raozas
  mobile-frontend/+native-intent.ts
  mobile-frontend/app.config.js
  mobile-frontend/app.json
  mobile-frontend/app/(app)/(tabs)/(home)/_layout.tsx
  mobile-frontend/app/(app)/(tabs)/(home)/index.tsx
  mobile-frontend/app/(app)/(tabs)/(home)/message/[id].tsx
  mobile-frontend/app/_layout.tsx
  mobile-frontend/components/MessageList.tsx
  mobile-frontend/components/card.tsx
  mobile-frontend/package-lock.json
  mobile-frontend/package.json
Labels: bug, enhancement

#100 input ichidagi sozni filteringga otkazish
  admin-panel-frontend/messages/en.json
  admin-panel-frontend/messages/ja.json
  admin-panel-frontend/messages/ru.json
  admin-panel-frontend/messages/uz.json
Labels: enhancement, good first issue

#109 Settings page UI updated
  mobile-frontend/app/(app)/(tabs)/(settings)/settings.tsx
Labels: enhancement

#114 group va ota-onalar createdagi input ichidagi sozdagi by name so'zini o'chirish
  admin-panel-frontend/messages/en.json
  admin-panel-frontend/messages/ja.json
  admin-panel-frontend/messages/ru.json
  admin-panel-frontend/messages/uz.json
Labels: bug

#113 112 switch mode in mobile
  mobile-frontend/app/(app)/(tabs)/(home)/index.tsx
  mobile-frontend/app/(app)/(tabs)/(home)/message/[id].tsx
  mobile-frontend/app/(app)/(tabs)/(settings)/change-psswd.tsx
  mobile-frontend/app/(app)/(tabs)/(settings)/settings.tsx
  mobile-frontend/app/(app)/(tabs)/_layout.tsx
  mobile-frontend/app/(app)/_layout.tsx
  mobile-frontend/app/_layout.tsx
  mobile-frontend/app/sign-in.tsx
  mobile-frontend/components/MessageList.tsx
  mobile-frontend/components/StudentSelector.tsx
  mobile-frontend/components/ThemeSwitcher.tsx
  mobile-frontend/components/atomic/input.tsx
  mobile-frontend/components/atomic/secure-input.tsx
  mobile-frontend/components/atomic/select.tsx
  mobile-frontend/components/card.tsx
  mobile-frontend/constants/theme.ts
  mobile-frontend/hooks/useThemeColor.ts
Labels: enhancement

#123 navlinks in mobile
  admin-panel-frontend/app/[locale]/(dashboard)/layout.tsx
  admin-panel-frontend/components/NavLink.tsx
  admin-panel-frontend/components/NavLinks.tsx
Labels: help wanted

#119 Mobile user long name wrap
  mobile-frontend/app/(app)/(tabs)/(settings)/settings.tsx
  mobile-frontend/components/ThemeSwitcher.tsx
Labels: bug, enhancement

#131 Refactor TypeScript configuration and improve code formatting across multiple files
  admin-panel-frontend/.eslintrc.json
  mobile-frontend/+native-intent.ts
  mobile-frontend/.editorconfig
  mobile-frontend/.eslintignore
  mobile-frontend/.eslintrc.js
  mobile-frontend/.prettierrc
  mobile-frontend/app.config.js
  mobile-frontend/app/(app)/(tabs)/(home)/_layout.tsx
  mobile-frontend/app/(app)/(tabs)/(home)/index.tsx
  mobile-frontend/app/(app)/(tabs)/(home)/message/[id].tsx
  mobile-frontend/app/(app)/(tabs)/(home)/student/[id].tsx
  mobile-frontend/app/(app)/(tabs)/(settings)/_layout.tsx
  mobile-frontend/app/(app)/(tabs)/(settings)/change-psswd.tsx
  mobile-frontend/app/(app)/(tabs)/(settings)/settings.tsx
  mobile-frontend/app/(app)/(tabs)/_layout.tsx
  mobile-frontend/app/(app)/_layout.tsx
  mobile-frontend/app/+html.tsx
  mobile-frontend/app/+not-found.tsx
  mobile-frontend/app/_layout.tsx
  mobile-frontend/app/new-psswd.tsx
  mobile-frontend/app/sign-in.tsx
  mobile-frontend/babel.config.js
  mobile-frontend/components/ExternalLink.tsx
  mobile-frontend/components/FontSizeSlider.tsx
  mobile-frontend/components/MessageList.tsx
  mobile-frontend/components/StudentSelector.tsx
  mobile-frontend/components/ThemeSwitcher.tsx
  mobile-frontend/components/ThemedText.tsx
  mobile-frontend/components/ThemedView.tsx
  mobile-frontend/components/__tests__/ThemedText-test.tsx
  mobile-frontend/components/atomic/button.tsx
  mobile-frontend/components/atomic/input.tsx
  mobile-frontend/components/atomic/secure-input.tsx
  mobile-frontend/components/atomic/select.tsx
  mobile-frontend/components/atomic/separator.tsx
  mobile-frontend/components/card.tsx
  mobile-frontend/components/navigation/TabBarIcon.tsx
  mobile-frontend/constants/Colors.ts
  mobile-frontend/constants/types.ts
  mobile-frontend/contexts/FontSizeContext.tsx
  mobile-frontend/contexts/auth-context.tsx
  mobile-frontend/contexts/i18n-context.tsx
  mobile-frontend/contexts/network-context.tsx
  mobile-frontend/contexts/student-context.tsx
  mobile-frontend/hooks/useColorScheme.ts
  mobile-frontend/hooks/useColorScheme.web.ts
  mobile-frontend/hooks/useStorageState.tsx
  mobile-frontend/hooks/useThemeColor.ts
  mobile-frontend/package-lock.json
  mobile-frontend/package.json
  mobile-frontend/public/.well-known/assetlinks.json
  mobile-frontend/translations/translation.ts
  mobile-frontend/tsconfig.json
  mobile-frontend/utils/deep-link-tester.ts
  mobile-frontend/utils/format.ts
  mobile-frontend/utils/queries.ts
  mobile-frontend/utils/server.ts
  mobile-frontend/utils/utils.ts
Labels: enhancement

#137 fix: pagination links
  backend/src/routes/admin-panel/post.ts
Labels: bug, help wanted
